name: WakeyWakey
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.10
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    PRODUCT_BUNDLE_IDENTIFIER: com.brndnsvr.WakeyWakey
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: CMFBMNG959
    CODE_SIGN_IDENTITY: Apple Development
    ENABLE_HARDENED_RUNTIME: YES
    # Debug-only arch restriction will be set in configurations below
configs:
  Debug: debug
  Release: release
targets:
  WakeyWakey:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: WakeyWakey
    resources:
      - path: WakeyWakey/Assets.xcassets
      - path: WakeyWakey/Resources/Info.plist
    settings:
      base:
        INFOPLIST_FILE: WakeyWakey/Resources/Info.plist
        ARCHS: arm64
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
        Release:
          ONLY_ACTIVE_ARCH: NO
    dependencies:
      - sdk: IOKit.framework
      - sdk: ApplicationServices.framework
    scheme:
      name: WakeyWakey
      testTargets: []
