name: WakeyWakey
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.10
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    PRODUCT_BUNDLE_IDENTIFIER: com.brndnsvr.WakeyWakey
    DEVELOPMENT_TEAM: ${WAKEY_TEAM_ID}
    ENABLE_HARDENED_RUNTIME: YES
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
configs:
  Debug: debug
  Release: release
targets:
  WakeyWakey:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: WakeyWakey
    resources:
      - path: WakeyWakey/Assets.xcassets
      - path: WakeyWakey/Resources/Info.plist
    settings:
      base:
        INFOPLIST_FILE: WakeyWakey/Resources/Info.plist
        ARCHS: arm64
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: Apple Development
        Release:
          ONLY_ACTIVE_ARCH: NO
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: Developer ID Application
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
          OTHER_CODE_SIGN_FLAGS: --timestamp
    dependencies:
      - sdk: IOKit.framework
      - sdk: ApplicationServices.framework
    scheme:
      name: WakeyWakey
      testTargets: []
